modLoader="javafml"
loaderVersion="[34,)"
license="LGPL-3.0"
[[mods]]
modId="janoeo_world"
version="${file.jarVersion}"
displayName="Janoeo - World"
authors="AlasDiablo, lIotaMiu, Egame257 and Safyrus"
description='''
Janoeo - World by AlasDiablo, lIotaMiu, Egame257 and Safyrus
'''
[[dependencies.janoeo_world]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.janoeo_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.janoeo_world]]
    modId="janoeo"
    mandatory=true
    versionRange="[4.4,)"
    ordering="AFTER"
    side="BOTH"